[
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/rlcompleter.py",
    "vulnerable_lines": [
      155
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/trace.py",
    "vulnerable_lines": [
      450
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/bdb.py",
    "vulnerable_lines": [
      583,
      597,
      604,
      605,
      617,
      842
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cProfile.py",
    "vulnerable_lines": [
      100
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/zipimport.py",
    "vulnerable_lines": [
      301
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/gettext.py",
    "vulnerable_lines": [
      204,
      212
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cgi.py",
    "vulnerable_lines": [
      871
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py",
    "vulnerable_lines": [
      701,
      1811,
      1832
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/profile.py",
    "vulnerable_lines": [
      422
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/code.py",
    "vulnerable_lines": [
      90
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc.py",
    "vulnerable_lines": [
      2054
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/optparse.py",
    "vulnerable_lines": [
      879
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pdb.py",
    "vulnerable_lines": [
      167,
      459,
      738,
      1250,
      1258,
      1260,
      1587,
      1673,
      1674
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/turtle.py",
    "vulnerable_lines": [
      189,
      327,
      3854,
      3857,
      3884,
      3885,
      3985
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pprint.py",
    "vulnerable_lines": [
      73
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py",
    "vulnerable_lines": [
      180,
      194,
      196,
      199,
      200,
      277,
      2219,
      2222,
      2255
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site.py",
    "vulnerable_lines": [
      186
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ast.py",
    "vulnerable_lines": [
      54
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/doctest.py",
    "vulnerable_lines": [
      1350,
      2646,
      2653
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py",
    "vulnerable_lines": [
      415,
      435,
      701,
      703
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/timeit.py",
    "vulnerable_lines": [
      134
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py",
    "vulnerable_lines": [
      871,
      2264,
      2298
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_pydecimal.py",
    "vulnerable_lines": [
      1038
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/imp.py",
    "vulnerable_lines": [
      170,
      190,
      215
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/runpy.py",
    "vulnerable_lines": [
      88
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/distutils/core.py",
    "vulnerable_lines": [
      177,
      215
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/test/test_pickling.py",
    "vulnerable_lines": [
      22
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/test/test_case.py",
    "vulnerable_lines": [
      1854
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/test/test_discovery.py",
    "vulnerable_lines": [
      530,
      553,
      580
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/test/test_runner.py",
    "vulnerable_lines": [
      1236
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/test/testmock/testmock.py",
    "vulnerable_lines": [
      56
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/test/testmock/testsentinel.py",
    "vulnerable_lines": [
      32
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_coroutines.py",
    "vulnerable_lines": [
      510,
      517
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_turtle.py",
    "vulnerable_lines": [
      175
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_fstring.py",
    "vulnerable_lines": [
      33,
      81,
      444,
      446,
      454,
      595,
      598,
      601,
      605,
      778,
      1209,
      1210
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_funcattrs.py",
    "vulnerable_lines": [
      94,
      102,
      168
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_binop.py",
    "vulnerable_lines": [
      298
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_descr.py",
    "vulnerable_lines": [
      77,
      94,
      108,
      122,
      141,
      160,
      218,
      219,
      231,
      238,
      1972,
      3139,
      3140,
      3142,
      3143,
      3145,
      3146,
      3218,
      3219,
      3221,
      3222,
      3224,
      3225,
      4576
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_pprint.py",
    "vulnerable_lines": [
      341,
      949,
      951,
      1030,
      1032
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_opcodes.py",
    "vulnerable_lines": [
      40,
      97,
      98,
      101,
      102,
      105,
      106,
      109,
      110,
      113,
      114,
      117,
      118,
      121,
      122,
      125,
      126
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_popen.py",
    "vulnerable_lines": [
      17,
      30
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_gettext.py",
    "vulnerable_lines": [
      439
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_list.py",
    "vulnerable_lines": [
      129,
      137,
      146,
      154,
      165,
      173,
      182,
      190
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_statistics.py",
    "vulnerable_lines": [
      2995
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_unicode.py",
    "vulnerable_lines": [
      216
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_contextlib.py",
    "vulnerable_lines": [
      183
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_capi.py",
    "vulnerable_lines": [
      154,
      159,
      885
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_gc.py",
    "vulnerable_lines": [
      225
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test___all__.py",
    "vulnerable_lines": [
      50,
      65
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_xml_etree.py",
    "vulnerable_lines": [
      176
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_class.py",
    "vulnerable_lines": [
      131,
      133
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_decorators.py",
    "vulnerable_lines": [
      33,
      188
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_source_encoding.py",
    "vulnerable_lines": [
      29,
      43,
      49,
      114,
      311
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_zipfile.py",
    "vulnerable_lines": [
      3085
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/_test_multiprocessing.py",
    "vulnerable_lines": [
      4013,
      4041,
      4266,
      4298
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_logging.py",
    "vulnerable_lines": [
      1749,
      1858,
      5213
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_print.py",
    "vulnerable_lines": [
      141,
      149,
      157,
      167,
      178,
      186
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_operator.py",
    "vulnerable_lines": [
      568
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_unpack.py",
    "vulnerable_lines": [
      163
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_urllib2.py",
    "vulnerable_lines": [
      41
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_ucn.py",
    "vulnerable_lines": [
      28
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_threading.py",
    "vulnerable_lines": [
      30
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_positional_only_arg.py",
    "vulnerable_lines": [
      358,
      359,
      360
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/re_tests.py",
    "vulnerable_lines": [
      44
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_time.py",
    "vulnerable_lines": [
      759,
      958,
      1086,
      1100
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_pickle.py",
    "vulnerable_lines": [
      88
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_iter.py",
    "vulnerable_lines": [
      114,
      121,
      127,
      190,
      198,
      207,
      215
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_pdb.py",
    "vulnerable_lines": [
      664,
      764,
      769
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/pickletester.py",
    "vulnerable_lines": [
      1424,
      3787,
      3820,
      3871,
      3874
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_module.py",
    "vulnerable_lines": [
      115
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_ordered_dict.py",
    "vulnerable_lines": [
      316,
      321,
      356,
      366,
      826
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_future.py",
    "vulnerable_lines": [
      103,
      110,
      120,
      122,
      148,
      176,
      370
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_configparser.py",
    "vulnerable_lines": [
      1724,
      1733,
      1744,
      1756,
      1770,
      1784,
      1797,
      1810,
      1823,
      1838,
      1850,
      1862
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/seq_tests.py",
    "vulnerable_lines": [
      425
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_posix.py",
    "vulnerable_lines": [
      581
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_dbm_dumb.py",
    "vulnerable_lines": [
      235
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_os.py",
    "vulnerable_lines": [
      613,
      670,
      3885,
      3898
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_itertools.py",
    "vulnerable_lines": [
      81,
      102,
      111,
      120,
      647,
      650,
      663,
      671,
      731,
      750,
      751,
      783,
      860,
      862,
      911,
      917,
      954,
      1639,
      1641,
      1652
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_decimal.py",
    "vulnerable_lines": [
      450,
      897,
      898,
      899,
      900,
      901,
      902,
      918,
      920,
      2088,
      2092,
      2096,
      2100,
      2558,
      2569,
      2576,
      2586,
      2593,
      2941,
      2978,
      4718,
      4726
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_unary.py",
    "vulnerable_lines": [
      31,
      32,
      33
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_array.py",
    "vulnerable_lines": [
      277,
      283,
      292,
      298,
      312,
      320,
      329,
      337,
      367,
      376,
      386,
      395,
      529
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_typing.py",
    "vulnerable_lines": [
      443,
      633,
      636,
      637,
      700,
      703,
      704,
      732,
      735,
      736,
      810,
      813,
      814,
      1305,
      1313,
      1325,
      1329,
      1333,
      1640,
      2658,
      2664,
      3168,
      3283,
      3294,
      3301,
      3332,
      4332,
      4973,
      4985,
      5258,
      5348,
      5570,
      5574,
      5584,
      5791,
      5891,
      5895,
      5902,
      5906,
      6557,
      6571,
      7132,
      7162,
      7175,
      7184
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_code.py",
    "vulnerable_lines": [
      182,
      345,
      510,
      705
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_bdb.py",
    "vulnerable_lines": [
      115,
      746,
      1036
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_named_expressions.py",
    "vulnerable_lines": [
      11,
      17,
      23,
      29,
      35,
      41,
      47,
      53,
      59,
      66,
      73,
      80,
      86,
      93,
      99,
      106,
      115,
      132,
      143,
      145,
      147,
      165,
      167,
      169,
      186,
      197,
      199,
      201,
      219,
      221,
      223,
      359,
      517,
      545
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_grammar.py",
    "vulnerable_lines": [
      137,
      149,
      183,
      184,
      189,
      338,
      446,
      448,
      458,
      473,
      490,
      495,
      499,
      503,
      836,
      840,
      1869,
      1878,
      1879,
      1883,
      1884,
      1885
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_bytes.py",
    "vulnerable_lines": [
      809,
      818,
      822,
      827,
      1681,
      1689,
      1698,
      1706,
      1911,
      1980
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_getpath.py",
    "vulnerable_lines": [
      1112
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/datetimetester.py",
    "vulnerable_lines": [
      269,
      780,
      1119,
      1404,
      2032,
      2346,
      3333
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_socket.py",
    "vulnerable_lines": [
      1723,
      1725,
      5845,
      5859
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_dis.py",
    "vulnerable_lines": [
      799,
      824,
      963,
      968,
      981,
      986,
      1000,
      1017
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_http_cookies.py",
    "vulnerable_lines": [
      214,
      437
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_scope.py",
    "vulnerable_lines": [
      345,
      376,
      482,
      617,
      646,
      702
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_ntpath.py",
    "vulnerable_lines": [
      55,
      71
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_exceptions.py",
    "vulnerable_lines": [
      104,
      180,
      183,
      2378
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test__locale.py",
    "vulnerable_lines": [
      194,
      195
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_enumerate.py",
    "vulnerable_lines": [
      72,
      76,
      83
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_descrtut.py",
    "vulnerable_lines": [
      69,
      74
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_utf8source.py",
    "vulnerable_lines": [
      38
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_cmd_line.py",
    "vulnerable_lines": [
      105,
      496
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_unpack_ex.py",
    "vulnerable_lines": [
      131
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_bool.py",
    "vulnerable_lines": [
      24,
      25,
      272,
      273
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_defaultdict.py",
    "vulnerable_lines": [
      62,
      150
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_compile.py",
    "vulnerable_lines": [
      67,
      79,
      82,
      87,
      89,
      91,
      108,
      134,
      175,
      176,
      177,
      178,
      179,
      180,
      181,
      182,
      183,
      184,
      185,
      186,
      187,
      188,
      189,
      190,
      191,
      192,
      193,
      194,
      195,
      196,
      197,
      198,
      218,
      219,
      223,
      224,
      229,
      230,
      338,
      340,
      342,
      344,
      346,
      348,
      350,
      352,
      596,
      598,
      600,
      602,
      603,
      605,
      626,
      706,
      850,
      1001,
      1209,
      1383
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_dataclasses.py",
    "vulnerable_lines": [
      2032,
      2037,
      3011,
      3016
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_sndhdr.py",
    "vulnerable_lines": [
      36
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_functools.py",
    "vulnerable_lines": [
      258,
      351,
      363,
      536,
      1231,
      1791
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_subprocess.py",
    "vulnerable_lines": [
      802,
      2143,
      2715,
      2963,
      3113,
      3131,
      3132,
      3138,
      3150,
      3159,
      3172,
      3199
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_multibytecodec.py",
    "vulnerable_lines": [
      63
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_peepholer.py",
    "vulnerable_lines": [
      19,
      546,
      556,
      573,
      576,
      578,
      580,
      583,
      585,
      587,
      589,
      591,
      593,
      596,
      599
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_tuple.py",
    "vulnerable_lines": [
      380,
      384,
      394,
      398
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_set.py",
    "vulnerable_lines": [
      234,
      247,
      254,
      260,
      929,
      1338,
      1348
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_doctest.py",
    "vulnerable_lines": [
      2878
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_ipaddress.py",
    "vulnerable_lines": [
      92
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_deque.py",
    "vulnerable_lines": [
      528,
      616,
      625,
      637,
      646,
      656,
      665,
      831,
      844,
      854
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_site.py",
    "vulnerable_lines": [
      156,
      501,
      521
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_dynamic.py",
    "vulnerable_lines": [
      79,
      88,
      90,
      92,
      98,
      106,
      132,
      144
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_sys_settrace.py",
    "vulnerable_lines": [
      476,
      1577,
      2522,
      2549,
      2713,
      2749,
      2761
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_inspect.py",
    "vulnerable_lines": [
      82,
      102,
      643,
      660,
      814,
      1581,
      1607,
      1608,
      1615,
      1621,
      1634,
      2339,
      2353,
      4052
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_tokenize.py",
    "vulnerable_lines": [
      986,
      990
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_int.py",
    "vulnerable_lines": [
      222
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_signal.py",
    "vulnerable_lines": [
      1045
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_longexp.py",
    "vulnerable_lines": [
      6
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_memoryio.py",
    "vulnerable_lines": [
      420,
      718,
      863
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_hash.py",
    "vulnerable_lines": [
      175
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_xml_dom_minicompat.py",
    "vulnerable_lines": [
      92,
      100
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/audit-tests.py",
    "vulnerable_lines": [
      147,
      152,
      154,
      243,
      247,
      251,
      255
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_keyword.py",
    "vulnerable_lines": [
      26
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_asyncgen.py",
    "vulnerable_lines": [
      94,
      102,
      112,
      121,
      131
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_re.py",
    "vulnerable_lines": [
      1218,
      2781
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/audiotests.py",
    "vulnerable_lines": [
      50
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_symtable.py",
    "vulnerable_lines": [
      233,
      239
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_float.py",
    "vulnerable_lines": [
      76,
      772,
      773
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_platform.py",
    "vulnerable_lines": [
      263
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_string_literals.py",
    "vulnerable_lines": [
      22,
      82,
      83,
      84,
      85,
      86,
      87,
      88,
      89,
      90,
      113,
      117,
      126,
      137,
      141,
      151,
      160,
      161,
      162,
      163,
      164,
      165,
      166,
      167,
      168,
      171,
      172,
      173,
      174,
      176,
      178,
      190,
      194,
      203,
      213,
      217,
      227,
      235,
      236,
      237,
      238,
      239,
      240,
      241,
      242,
      245,
      246,
      249,
      250,
      261,
      262,
      263
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_complex.py",
    "vulnerable_lines": [
      541,
      657,
      664
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_codeop.py",
    "vulnerable_lines": [
      34,
      35,
      40,
      41,
      295
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/time_hashlib.py",
    "vulnerable_lines": [
      48,
      49,
      53,
      57,
      63
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_pickletools.py",
    "vulnerable_lines": [
      14,
      27,
      32,
      54,
      59
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_collections.py",
    "vulnerable_lines": [
      119,
      126,
      683,
      684,
      2184,
      2185
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_unicodedata.py",
    "vulnerable_lines": [
      242
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_range.py",
    "vulnerable_lines": [
      373,
      393,
      397,
      403,
      416,
      428,
      441
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_tcl.py",
    "vulnerable_lines": [
      56,
      57,
      61,
      65,
      91,
      96,
      100,
      105,
      119,
      121,
      127,
      128,
      130,
      131,
      202,
      203,
      204,
      216,
      217,
      233,
      234
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_uuid.py",
    "vulnerable_lines": [
      344,
      459,
      461,
      463
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_plistlib.py",
    "vulnerable_lines": [
      556
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_long.py",
    "vulnerable_lines": [
      769
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_builtin.py",
    "vulnerable_lines": [
      142,
      147,
      153,
      371,
      405,
      453,
      509,
      615,
      616,
      617,
      620,
      621,
      622,
      623,
      627,
      628,
      638,
      642,
      652,
      654,
      655,
      656,
      674,
      676,
      677,
      678,
      681,
      682,
      690,
      707,
      709,
      714,
      724,
      761,
      776,
      807,
      815,
      1137,
      1196,
      1719,
      2178
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test__xxsubinterpreters.py",
    "vulnerable_lines": [
      98
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_format.py",
    "vulnerable_lines": [
      541
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_genericalias.py",
    "vulnerable_lines": [
      395
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_dict.py",
    "vulnerable_lines": [
      39,
      819,
      1102,
      1105,
      1111,
      1121,
      1130,
      1133,
      1143,
      1146,
      1149,
      1158,
      1161,
      1167,
      1177,
      1186,
      1189,
      1199,
      1202,
      1205
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_minidom.py",
    "vulnerable_lines": [
      1613
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_ast.py",
    "vulnerable_lines": [
      855,
      1123,
      1124,
      1125,
      1126,
      1127,
      1128,
      1129,
      1131,
      1132,
      1133,
      1134,
      1135,
      1136,
      1137,
      1144,
      1146,
      1152,
      1153,
      1154,
      1155,
      1156,
      1157,
      1158,
      1159,
      1160,
      1161,
      1162,
      1163,
      1164,
      1178,
      1179,
      1180,
      1186,
      1193,
      1197,
      1222,
      1814,
      1901,
      1913
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_super.py",
    "vulnerable_lines": [
      102
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_traceback.py",
    "vulnerable_lines": [
      1317
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_pkg.py",
    "vulnerable_lines": [
      70
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_types.py",
    "vulnerable_lines": [
      866,
      1784
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_pathlib.py",
    "vulnerable_lines": [
      297,
      299,
      701,
      2438
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_enum.py",
    "vulnerable_lines": [
      2458
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_eof.py",
    "vulnerable_lines": [
      14,
      25,
      52,
      55
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_random.py",
    "vulnerable_lines": [
      373,
      1324
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/double_const.py",
    "vulnerable_lines": [
      18,
      21
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_json/test_unicode.py",
    "vulnerable_lines": [
      86
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_json/test_decode.py",
    "vulnerable_lines": [
      28
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_peg_generator/test_pegen.py",
    "vulnerable_lines": [
      491,
      497,
      540,
      637,
      795,
      894
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_importlib/test_spec.py",
    "vulnerable_lines": [
      249,
      251,
      256,
      345,
      357,
      367,
      380,
      396
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_importlib/test_abc.py",
    "vulnerable_lines": [
      513,
      560,
      661,
      691,
      801
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_importlib/test_lazy.py",
    "vulnerable_lines": [
      51
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_importlib/test_main.py",
    "vulnerable_lines": [
      233
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_importlib/frozen/test_loader.py",
    "vulnerable_lines": [
      235
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_warnings/__init__.py",
    "vulnerable_lines": [
      484
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_import/__init__.py",
    "vulnerable_lines": [
      139,
      148,
      232,
      784
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_zoneinfo/test_zoneinfo.py",
    "vulnerable_lines": [
      1410,
      1415,
      1427,
      1428,
      1438,
      1443,
      1481,
      1488,
      1495
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_email/test_pickleable.py",
    "vulnerable_lines": [
      35,
      71
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_asyncio/test_streams.py",
    "vulnerable_lines": [
      799,
      976,
      985
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_asyncio/test_subprocess.py",
    "vulnerable_lines": [
      114,
      140,
      175,
      188,
      208,
      234,
      286,
      314,
      333,
      352,
      371,
      390,
      409,
      428,
      431,
      448,
      467,
      504,
      553,
      581,
      598,
      602,
      606,
      630,
      633,
      716
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/test/test_asyncio/test_events.py",
    "vulnerable_lines": [
      1754,
      1757,
      1778,
      1846,
      1862,
      1884,
      1903,
      1924,
      1949,
      1994,
      2529
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/util.py",
    "vulnerable_lines": [
      453
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/sharedctypes.py",
    "vulnerable_lines": [
      153
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/managers.py",
    "vulnerable_lines": [
      965
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/configobj.py",
    "vulnerable_lines": [
      205
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/six.py",
    "vulnerable_lines": [
      735
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/astroid/inference.py",
    "vulnerable_lines": [
      1006
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/config.py",
    "vulnerable_lines": [
      185
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/cli.py",
    "vulnerable_lines": [
      141,
      142,
      960
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylint/lint/pylinter.py",
    "vulnerable_lines": [
      1187
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylint/checkers/strings.py",
    "vulnerable_lines": [
      746,
      946,
      947,
      1023
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylint/config/utils.py",
    "vulnerable_lines": [
      169
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pylint/config/config_initialization.py",
    "vulnerable_lines": [
      48
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygments/lexers/_julia_builtins.py",
    "vulnerable_lines": [
      140,
      351
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygments/lexers/__init__.py",
    "vulnerable_lines": [
      140
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygments/lexers/special.py",
    "vulnerable_lines": [
      112
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygments/formatters/__init__.py",
    "vulnerable_lines": [
      101
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jinja2/debug.py",
    "vulnerable_lines": [
      145
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jinja2/lexer.py",
    "vulnerable_lines": [
      661
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jinja2/environment.py",
    "vulnerable_lines": [
      1222
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jinja2/nativetypes.py",
    "vulnerable_lines": [
      40
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/jinja2/nodes.py",
    "vulnerable_lines": [
      579
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/routing/rules.py",
    "vulnerable_lines": [
      688
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/debug/console.py",
    "vulnerable_lines": [
      180,
      216
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/debug/tbtools.py",
    "vulnerable_lines": [
      377,
      378
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/werkzeug/debug/__init__.py",
    "vulnerable_lines": [
      133,
      134,
      379
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bs4/tests/test_soup.py",
    "vulnerable_lines": [
      392,
      401
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bs4/tests/test_lxml.py",
    "vulnerable_lines": [
      197
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bs4/tests/__init__.py",
    "vulnerable_lines": [
      352,
      982
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bs4/tests/test_pageelement.py",
    "vulnerable_lines": [
      664,
      703
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bs4/tests/test_htmlparser.py",
    "vulnerable_lines": [
      32
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Foundation/_nsobject.py",
    "vulnerable_lines": [
      13
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida_tools/_repl_magic.py",
    "vulnerable_lines": [
      167
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida_tools/repl.py",
    "vulnerable_lines": [
      463
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pytz/__init__.py",
    "vulnerable_lines": [
      283,
      486,
      488
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/isort/literal.py",
    "vulnerable_lines": [
      54
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/regex/test_regex.py",
    "vulnerable_lines": [
      3800
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bandit/plugins/injection_paramiko.py",
    "vulnerable_lines": [
      27
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bandit/plugins/exec.py",
    "vulnerable_lines": [
      21
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bandit/plugins/yaml_load.py",
    "vulnerable_lines": [
      30,
      51
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bandit/formatters/screen.py",
    "vulnerable_lines": [
      23
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bandit/formatters/html.py",
    "vulnerable_lines": [
      126
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bandit/formatters/yaml.py",
    "vulnerable_lines": [
      42
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bandit/formatters/text.py",
    "vulnerable_lines": [
      22
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/bandit/formatters/json.py",
    "vulnerable_lines": [
      46
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wrapt/decorators.py",
    "vulnerable_lines": [
      23
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PIL/ImageMath.py",
    "vulnerable_lines": [
      222,
      255
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PIL/Image.py",
    "vulnerable_lines": [
      3187
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/to_process.py",
    "vulnerable_lines": [
      75
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py",
    "vulnerable_lines": [
      1105
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_internal/utils/setuptools_build.py",
    "vulnerable_lines": [
      10,
      43
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/six.py",
    "vulnerable_lines": [
      735
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/typing_extensions.py",
    "vulnerable_lines": [
      914
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pygments/lexers/__init__.py",
    "vulnerable_lines": [
      134
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pygments/formatters/__init__.py",
    "vulnerable_lines": [
      91
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pyparsing/results.py",
    "vulnerable_lines": [
      50
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/cachecontrol/serialize.py",
    "vulnerable_lines": [
      151
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/rich/markup.py",
    "vulnerable_lines": [
      184
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip/_vendor/pkg_resources/__init__.py",
    "vulnerable_lines": [
      1462,
      1469
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PyObjCTools/TestSupport.py",
    "vulnerable_lines": [
      1080
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/attr/_make.py",
    "vulnerable_lines": [
      290,
      295,
      322,
      350
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/cli.py",
    "vulnerable_lines": [
      35,
      38
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ptyprocess/ptyprocess.py",
    "vulnerable_lines": [
      92
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rich/markup.py",
    "vulnerable_lines": [
      184
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telebot/handler_backends.py",
    "vulnerable_lines": [
      147,
      158
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/sandbox.py",
    "vulnerable_lines": [
      46
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/launch.py",
    "vulnerable_lines": [
      32
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py",
    "vulnerable_lines": [
      335
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_vendor/typing_extensions.py",
    "vulnerable_lines": [
      1258
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_vendor/jaraco/functools.py",
    "vulnerable_lines": [
      519
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_vendor/pyparsing/results.py",
    "vulnerable_lines": [
      50
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/config/expand.py",
    "vulnerable_lines": [
      82
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py",
    "vulnerable_lines": [
      977
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py",
    "vulnerable_lines": [
      227,
      267
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py",
    "vulnerable_lines": [
      1472,
      1479
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/_vendor/jaraco/functools.py",
    "vulnerable_lines": [
      519
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/_vendor/pyparsing/results.py",
    "vulnerable_lines": [
      50
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/virtualenv/activation/python/activate_this.py",
    "vulnerable_lines": [
      3,
      14
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/virtualenv/create/creator.py",
    "vulnerable_lines": [
      199
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/objc/_lazyimport.py",
    "vulnerable_lines": [
      431
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/objc/_descriptors.py",
    "vulnerable_lines": [
      391,
      393
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/core/cache/backends/db.py",
    "vulnerable_lines": [
      96
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/core/cache/backends/filebased.py",
    "vulnerable_lines": [
      36,
      69
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/core/cache/backends/locmem.py",
    "vulnerable_lines": [
      42,
      72
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/core/management/commands/shell.py",
    "vulnerable_lines": [
      78,
      117,
      127
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/core/serializers/pyyaml.py",
    "vulnerable_lines": [
      78
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/core/serializers/base.py",
    "vulnerable_lines": [
      26
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/test/runner.py",
    "vulnerable_lines": [
      181
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/template/smartif.py",
    "vulnerable_lines": [
      58,
      84,
      97,
      98,
      99,
      100,
      101,
      102,
      103,
      104,
      105,
      106,
      107,
      108,
      109,
      137
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/template/defaulttags.py",
    "vulnerable_lines": [
      315,
      877
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/contrib/gis/serializers/geojson.py",
    "vulnerable_lines": [
      63
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/django/db/migrations/questioner.py",
    "vulnerable_lines": [
      140
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/temp.py",
    "vulnerable_lines": [
      71,
      72,
      88,
      220,
      221
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/_dill.py",
    "vulnerable_lines": [
      251,
      921,
      979
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/source.py",
    "vulnerable_lines": [
      60,
      82,
      178,
      395,
      539,
      540,
      707
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/objtypes.py",
    "vulnerable_lines": [
      18
    ]
  },
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/tests/test_module.py",
    "vulnerable_lines": [
      72
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/tests/test_nested.py",
    "vulnerable_lines": [
      67,
      68,
      69,
      75,
      77,
      82,
      88,
      99,
      106
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/tests/test_functions.py",
    "vulnerable_lines": [
      33,
      104
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/tests/test_classdef.py",
    "vulnerable_lines": [
      233
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/dill/tests/test_objects.py",
    "vulnerable_lines": [
      42
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/git/util.py",
    "vulnerable_lines": [
      279,
      294
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/tests/test_exceptions.py",
    "vulnerable_lines": [
      40
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py",
    "vulnerable_lines": [
      2386,
      2390,
      2394
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/ttk.py",
    "vulnerable_lines": [
      495
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/tix.py",
    "vulnerable_lines": [
      212,
      214,
      215,
      221
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dbm/dumb.py",
    "vulnerable_lines": [
      106
    ]
  },
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/_bootstrap.py",
    "vulnerable_lines": [
      287,
      600,
      982
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py",
    "vulnerable_lines": [
      169
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/main.py",
    "vulnerable_lines": [
      158
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/fixes/fix_input.py",
    "vulnerable_lines": [
      1,
      20
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/fixes/fix_exec.py",
    "vulnerable_lines": [
      7,
      9
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/fixes/fix_execfile.py",
    "vulnerable_lines": [
      7
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/tests/test_parser.py",
    "vulnerable_lines": [
      701
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/tests/test_fixers.py",
    "vulnerable_lines": [
      537,
      542,
      547,
      552,
      557,
      562,
      567,
      573,
      581,
      585,
      1204,
      1208,
      1212,
      1216,
      1220,
      1224,
      1229,
      1233,
      1953,
      1957,
      1962,
      1966,
      1969,
      1972,
      1977,
      1982,
      1987,
      1992
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/tests/data/infinite_recursion.py",
    "vulnerable_lines": [
      2244
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/tests/data/py2_test_grammar.py",
    "vulnerable_lines": [
      43,
      53,
      137,
      945,
      953,
      954,
      958,
      959,
      960
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/tests/data/py3_test_grammar.py",
    "vulnerable_lines": [
      47,
      59,
      171,
      929,
      938,
      939,
      943,
      944,
      945
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/pgen2/pgen.py",
    "vulnerable_lines": [
      88
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/pgen2/literals.py",
    "vulnerable_lines": [
      4
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/pgen2/grammar.py",
    "vulnerable_lines": [
      100
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib2to3/pgen2/conv.py",
    "vulnerable_lines": [
      187,
      213
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/pyshell.py",
    "vulnerable_lines": [
      286,
      764,
      781
    ]
  },
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/run.py",
    "vulnerable_lines": [
      100,
      578
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/debugobj.py",
    "vulnerable_lines": [
      35
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/rpc.py",
    "vulnerable_lines": [
      388
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/calltip.py",
    "vulnerable_lines": [
      140
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/autocomplete.py",
    "vulnerable_lines": [
      185,
      189,
      221
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/idle_test/test_run.py",
    "vulnerable_lines": [
      52,
      68,
      71
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/idlelib/idle_test/test_squeezer.py",
    "vulnerable_lines": [
      134
    ]
  },
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pydoc_data/topics.py",
    "vulnerable_lines": [
      1419,
      4740,
      4742,
      4746,
      4841,
      5406,
      5414,
      5539,
      5540,
      5698,
      5763,
      5771,
      6997,
      7003,
      7525,
      7808,
      7872,
      7880,
      10228,
      10231
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py",
    "vulnerable_lines": [
      434
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py",
    "vulnerable_lines": [
      517
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py",
    "vulnerable_lines": [
      1653
    ]
  },
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/subprocess.py",
    "vulnerable_lines": [
      212,
      218
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {
    "status": "Potential RCE vulnerability found",
    "file_path": "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/config.py",
    "vulnerable_lines": [
      138,
      142,
      144
    ]
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
]
